const{createClient}=require('@supabase/supabase-js');
const s=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY);
const o='bed3e621-d93c-4e89-bfc4-a0fcea61b8fd';
(async()=>{
const{data,error}=await s.from('knowledge_base').insert([
{organization_id:o,category:'mission',title:'Mission Statement',content:'The Foundation for Affordable Instruction and Tenancy Hope (FAITH Foundation) exists to help economically disadvantaged individuals and families achieve sustainable homeownership. We serve single mothers, veterans, individuals in recovery and re-entry, and other marginalized populations by providing down payment assistance vouchers, financial literacy education, and access to affordable modular housing. Our mission is to break the cycle of housing insecurity by combining direct financial assistance with comprehensive homebuyer education, empowering participants to build generational wealth through homeownership.'},
{organization_id:o,category:'vision',title:'Vision Statement',content:'The FAITH Foundation envisions a future where every economically disadvantaged family has a viable pathway to homeownership. We aim to become the leading national model for nonprofit-driven affordable housing by combining modular home technology, corporate giving partnerships, and wraparound financial education. Within five years we intend to help 500 families achieve homeownership across Texas and expand nationally.'},
{organization_id:o,category:'need_statement',title:'Housing Affordability Crisis',content:'The US faces a critical affordable housing shortage with over 7.3 million affordable rental homes missing nationwide. In Texas the median home price increased over 40 percent since 2020. Single mothers head 10 million households nationally with homeownership rates 30 points below married couples. Veterans face barriers including service-connected disabilities and employment gaps. Formerly incarcerated individuals encounter credit damage and landlord screening barriers. These populations are trapped in expensive rental cycles unable to save for down payments. Traditional assistance programs have long waitlists leaving a critical gap the FAITH Foundation addresses through voucher-based down payment assistance.'},
{organization_id:o,category:'program_description',title:'Down Payment Assistance Voucher Program',content:'The FAITH Foundation provides vouchers of up to 2500 dollars toward down payment costs on discounted modular housing units through partner Bright Box Homes. Program pathway: (1) Application and eligibility screening (2) Enrollment in mandatory Financial Literacy and Credit Repair Education Seminars (3) Matching with modular home inventory at discounted rates (4) Voucher issuance and closing assistance. Available homes include 20x20 and 20x40 expandable container homes, Apple cabins and space capsule units.'},
{organization_id:o,category:'program_description',title:'Financial Literacy Education',content:'The FAITH Foundation provides financial literacy and credit repair education seminars covering budgeting, credit reports, credit repair strategies, mortgage preparation, loan terms, homeownership financial planning, and avoiding predatory lending. Completion is prerequisite for voucher issuance. Offered in-person and virtual.'},
{organization_id:o,category:'program_description',title:'Land Acquisition and Site Development',content:'Long-term goals include acquiring land for modular home communities, site development with utilities and infrastructure, sourcing materials through grants and donations, overseeing construction of modular homes, and creating planned affordable communities. Vertically integrated model controls costs passing savings to homebuyers.'},
{organization_id:o,category:'impact',title:'Projected Community Impact',content:'Each family saves 3000-5000 dollars annually transitioning to homeownership. Net worth increases 40x vs renting. Children score 9 percent higher in math and 7 percent higher in reading. Stable housing reduces ER visits by 18 percent. Every dollar in down payment assistance generates 16 dollars in local economic activity. Education seminars improve credit scores 50-80 points in 12 months. Veterans show 25 percent better VA treatment adherence. Re-entry participants show 43 percent lower recidivism.'},
{organization_id:o,category:'capacity',title:'Organizational Capacity',content:'FAITH Foundation is a certified 501c3 statutory foundation incorporated in Wyoming, EIN 33-2640449, at 209 Surecast Drive Suite 105 Burnet Texas 78611. Phone 888-497-6620. Founded 18 months ago with Supabase data management, Benavora grant platform, and corporate partnerships. Lean overhead with leadership in real estate, construction, and community development.'},
{organization_id:o,category:'sustainability',title:'Financial Sustainability Model',content:'Cornerstone is Bright Box Homes partnership donating 2500 dollars per home sold. Supplemented by grants, donations, government programs (HOME, CDBG), and CDFI partnerships. Self-reinforcing model where home purchases generate Foundation funding. Land acquisition builds appreciating assets reducing per-unit costs.'},
{organization_id:o,category:'partnerships',title:'Bright Box Homes Strategic Partnership',content:'Bright Box Homes donates 2500 dollars to FAITH Foundation for every home sold through any channel. Offers modular housing at discounted rates to voucher recipients. Models include 20x20 and 20x40 expandable container homes, Apple cabins and space capsule units. Partnership aligns both missions.'},
{organization_id:o,category:'organizational_history',title:'Founding and Development',content:'FAITH Foundation established 18 months ago as 501c3 in Wyoming. Founding vision combined direct voucher assistance, financial education, and affordable modular housing access. Since founding: secured certification, established Bright Box partnership, developed voucher program, launched financial literacy curriculum, deployed Benavora platform, begun outreach across central Texas.'},
{organization_id:o,category:'budget_justification',title:'Program Budget Framework',content:'Four areas: Direct Assistance (vouchers at 2500 per family), Education Programs (instructors, materials, venues, virtual platforms), Housing Development (land, site prep, modular homes, construction), Operations (staff, technology, insurance, legal, admin below 15 percent). Voucher funding flows entirely to participants. Housing development generates appreciating assets.'}
]);
if(error)console.log('ERROR:',error.message);
else console.log('SUCCESS: Inserted',data.length,'entries');
})();
