-- ============================================================================
-- PT-09-002 schema extension -- applied on top of pt05-schema.sql +
-- pt05-002-schema-extension.sql + pt05-004-schema-extension.sql, against the
-- SAME local pt05-local-stack (never production).
--
-- Auto-generated by scripts/audit/pt09-002-gen-schema-extension.mjs from
-- test-evidence/pt-06/live-schema.json (a real, read-only production schema
-- snapshot). Two deliberate simplifications vs. the real production DDL:
--   1. USER-DEFINED (enum) columns -> plain text (no enum type recreated).
--   2. Every non-id column is nullable, NOT NULL dropped.
-- Both are so that a scaffolding gap can never masquerade as a real agent
-- code defect in this phase's WIRED-NO-OUTPUT / ERROR-SWALLOWED verdicts.
-- See the generator script's header comment for the full rationale.
-- ============================================================================

-- Widen tables pt05 already created with every real production column
-- they're missing (ADD COLUMN IF NOT EXISTS, idempotent).
-- widen organizations
alter table organizations add column if not exists id uuid;
alter table organizations add column if not exists name text;
alter table organizations add column if not exists dba text;
alter table organizations add column if not exists ein text;
alter table organizations add column if not exists tax_status text;
alter table organizations add column if not exists mission_statement text;
alter table organizations add column if not exists vision_statement text;
alter table organizations add column if not exists founding_date date;
alter table organizations add column if not exists founder_name text;
alter table organizations add column if not exists founder_bio text;
alter table organizations add column if not exists service_area text;
alter table organizations add column if not exists target_population text;
alter table organizations add column if not exists annual_budget numeric;
alter table organizations add column if not exists total_staff integer;
alter table organizations add column if not exists total_volunteers integer;
alter table organizations add column if not exists website text;
alter table organizations add column if not exists phone text;
alter table organizations add column if not exists email text;
alter table organizations add column if not exists address_line1 text;
alter table organizations add column if not exists address_line2 text;
alter table organizations add column if not exists city text;
alter table organizations add column if not exists state text;
alter table organizations add column if not exists zip text;
alter table organizations add column if not exists logo_url text;
alter table organizations add column if not exists stripe_customer_id text;
alter table organizations add column if not exists subscription_tier text;
alter table organizations add column if not exists created_at timestamptz;
alter table organizations add column if not exists updated_at timestamptz;
alter table organizations add column if not exists onboarding_completed boolean;
alter table organizations add column if not exists onboarding_completed_at timestamptz;
alter table organizations add column if not exists onboarding_step integer;
alter table organizations add column if not exists contact_email text;
alter table organizations add column if not exists white_label_config jsonb;
alter table organizations add column if not exists onboarding_progress jsonb;
alter table organizations add column if not exists donor_discovery_scoring_weights jsonb;
alter table organizations add column if not exists extended_profile jsonb;
-- widen profiles
alter table profiles add column if not exists id uuid;
alter table profiles add column if not exists organization_id uuid;
alter table profiles add column if not exists email text;
alter table profiles add column if not exists full_name text;
alter table profiles add column if not exists role text;
alter table profiles add column if not exists avatar_url text;
alter table profiles add column if not exists last_login_at timestamptz;
alter table profiles add column if not exists created_at timestamptz;
alter table profiles add column if not exists updated_at timestamptz;
alter table profiles add column if not exists command_center_layout jsonb;
alter table profiles add column if not exists restricted_onboarding_edit boolean;
-- widen funders
alter table funders add column if not exists id uuid;
alter table funders add column if not exists organization_id uuid;
alter table funders add column if not exists name text;
alter table funders add column if not exists category text;
alter table funders add column if not exists description text;
alter table funders add column if not exists website text;
alter table funders add column if not exists giving_portal_url text;
alter table funders add column if not exists portal_login_status text;
alter table funders add column if not exists annual_giving_budget numeric;
alter table funders add column if not exists geographic_focus text;
alter table funders add column if not exists preferred_application_method text;
alter table funders add column if not exists has_giving_page boolean;
alter table funders add column if not exists notes text;
alter table funders add column if not exists last_contacted_at timestamptz;
alter table funders add column if not exists created_at timestamptz;
alter table funders add column if not exists updated_at timestamptz;
alter table funders add column if not exists portal_status text;
alter table funders add column if not exists portal_last_checked_at timestamptz;
alter table funders add column if not exists portal_response_time_ms integer;
alter table funders add column if not exists type text;
alter table funders add column if not exists portal_review_status text;
alter table funders add column if not exists contact_email text;
alter table funders add column if not exists automation_level text;
alter table funders add column if not exists automation_notes text;
-- widen opportunities
alter table opportunities add column if not exists id uuid;
alter table opportunities add column if not exists organization_id uuid;
alter table opportunities add column if not exists funder_id uuid;
alter table opportunities add column if not exists name text;
alter table opportunities add column if not exists category text;
alter table opportunities add column if not exists description text;
alter table opportunities add column if not exists amount_available numeric;
alter table opportunities add column if not exists amount_min numeric;
alter table opportunities add column if not exists amount_max numeric;
alter table opportunities add column if not exists deadline timestamptz;
alter table opportunities add column if not exists url text;
alter table opportunities add column if not exists eligibility_requirements text;
alter table opportunities add column if not exists required_documents text[];
alter table opportunities add column if not exists application_method text;
alter table opportunities add column if not exists recurrence text;
alter table opportunities add column if not exists geographic_restrictions text;
alter table opportunities add column if not exists eligibility_score integer;
alter table opportunities add column if not exists recommendation text;
alter table opportunities add column if not exists recommendation_reasoning text;
alter table opportunities add column if not exists status text;
alter table opportunities add column if not exists source text;
alter table opportunities add column if not exists discovered_at timestamptz;
alter table opportunities add column if not exists created_at timestamptz;
alter table opportunities add column if not exists updated_at timestamptz;
alter table opportunities add column if not exists match_percentage integer;
alter table opportunities add column if not exists source_type text;
alter table opportunities add column if not exists opportunity_documents jsonb;
alter table opportunities add column if not exists is_high_priority boolean;
alter table opportunities add column if not exists match_mismatch_reasons text[];
-- widen applications
alter table applications add column if not exists id uuid;
alter table applications add column if not exists organization_id uuid;
alter table applications add column if not exists opportunity_id uuid;
alter table applications add column if not exists stage text;
alter table applications add column if not exists assigned_user_id uuid;
alter table applications add column if not exists requested_amount numeric;
alter table applications add column if not exists submitted_at timestamptz;
alter table applications add column if not exists awarded_amount numeric;
alter table applications add column if not exists draft_content text;
alter table applications add column if not exists draft_template_type text;
alter table applications add column if not exists draft_confidence_score integer;
alter table applications add column if not exists draft_knowledge_sources jsonb;
alter table applications add column if not exists notes text;
alter table applications add column if not exists created_at timestamptz;
alter table applications add column if not exists updated_at timestamptz;
alter table applications add column if not exists auto_generated boolean;
alter table applications add column if not exists pending_review boolean;
alter table applications add column if not exists draft_source text;
alter table applications add column if not exists budget_data jsonb;
alter table applications add column if not exists compliance_check_result jsonb;
alter table applications add column if not exists fit_analysis jsonb;
alter table applications add column if not exists twin_powered boolean;
alter table applications add column if not exists twin_completeness integer;
alter table applications add column if not exists platform_patterns_applied integer;
alter table applications add column if not exists knowledge_patterns_applied jsonb;
-- widen draft_versions
alter table draft_versions add column if not exists id uuid;
alter table draft_versions add column if not exists organization_id uuid;
alter table draft_versions add column if not exists opportunity_id uuid;
alter table draft_versions add column if not exists application_id uuid;
alter table draft_versions add column if not exists template_type text;
alter table draft_versions add column if not exists content text;
alter table draft_versions add column if not exists confidence_score integer;
alter table draft_versions add column if not exists knowledge_sources jsonb;
alter table draft_versions add column if not exists version_number integer;
alter table draft_versions add column if not exists humanization_status text;
alter table draft_versions add column if not exists source text;
alter table draft_versions add column if not exists created_by uuid;
alter table draft_versions add column if not exists created_at timestamptz;
-- widen contacts
alter table contacts add column if not exists id uuid;
alter table contacts add column if not exists organization_id uuid;
alter table contacts add column if not exists funder_id uuid;
alter table contacts add column if not exists name text;
alter table contacts add column if not exists title text;
alter table contacts add column if not exists email text;
alter table contacts add column if not exists phone text;
alter table contacts add column if not exists preferred_contact_method text;
alter table contacts add column if not exists relationship text;
alter table contacts add column if not exists last_contacted_at timestamptz;
alter table contacts add column if not exists notes text;
alter table contacts add column if not exists created_at timestamptz;
alter table contacts add column if not exists updated_at timestamptz;
-- widen donor_discovery_prospects
alter table donor_discovery_prospects add column if not exists id uuid;
alter table donor_discovery_prospects add column if not exists organization_id uuid;
alter table donor_discovery_prospects add column if not exists directory_id uuid;
alter table donor_discovery_prospects add column if not exists request_id uuid;
alter table donor_discovery_prospects add column if not exists score integer;
alter table donor_discovery_prospects add column if not exists score_rationale text;
alter table donor_discovery_prospects add column if not exists pipeline_stage text;
alter table donor_discovery_prospects add column if not exists notes text;
alter table donor_discovery_prospects add column if not exists assigned_to uuid;
alter table donor_discovery_prospects add column if not exists created_at timestamptz;
-- widen deadlines
alter table deadlines add column if not exists id uuid;
alter table deadlines add column if not exists organization_id uuid;
alter table deadlines add column if not exists application_id uuid;
alter table deadlines add column if not exists opportunity_id uuid;
alter table deadlines add column if not exists deadline_type text;
alter table deadlines add column if not exists due_date date;
alter table deadlines add column if not exists title text;
alter table deadlines add column if not exists description text;
alter table deadlines add column if not exists is_completed boolean;
alter table deadlines add column if not exists completed_at timestamptz;
alter table deadlines add column if not exists reminder_30d_sent boolean;
alter table deadlines add column if not exists reminder_14d_sent boolean;
alter table deadlines add column if not exists reminder_7d_sent boolean;
alter table deadlines add column if not exists reminder_3d_sent boolean;
alter table deadlines add column if not exists reminder_1d_sent boolean;
alter table deadlines add column if not exists created_at timestamptz;
alter table deadlines add column if not exists updated_at timestamptz;
alter table deadlines add column if not exists google_calendar_event_id text;
-- widen knowledge_base
alter table knowledge_base add column if not exists id uuid;
alter table knowledge_base add column if not exists organization_id uuid;
alter table knowledge_base add column if not exists category text;
alter table knowledge_base add column if not exists title text;
alter table knowledge_base add column if not exists content text;
alter table knowledge_base add column if not exists is_proven boolean;
alter table knowledge_base add column if not exists proven_count integer;
alter table knowledge_base add column if not exists funder_categories text[];
alter table knowledge_base add column if not exists keywords text[];
alter table knowledge_base add column if not exists version integer;
alter table knowledge_base add column if not exists created_by uuid;
alter table knowledge_base add column if not exists created_at timestamptz;
alter table knowledge_base add column if not exists updated_at timestamptz;
-- widen organizational_digital_twins
alter table organizational_digital_twins add column if not exists id uuid;
alter table organizational_digital_twins add column if not exists org_id uuid;
alter table organizational_digital_twins add column if not exists organization_id uuid;
alter table organizational_digital_twins add column if not exists mission text;
alter table organizational_digital_twins add column if not exists vision text;
alter table organizational_digital_twins add column if not exists service_areas text[];
alter table organizational_digital_twins add column if not exists programs jsonb;
alter table organizational_digital_twins add column if not exists financial_profile jsonb;
alter table organizational_digital_twins add column if not exists board_composition jsonb;
alter table organizational_digital_twins add column if not exists proven_narrative_patterns text[];
alter table organizational_digital_twins add column if not exists key_strengths text[];
alter table organizational_digital_twins add column if not exists known_weaknesses text[];
alter table organizational_digital_twins add column if not exists twin_completeness_score integer;
alter table organizational_digital_twins add column if not exists last_rebuilt_at timestamptz;
alter table organizational_digital_twins add column if not exists created_at timestamptz;
alter table organizational_digital_twins add column if not exists updated_at timestamptz;

-- agent_decisions (16 columns, from production live-schema.json)
create table if not exists agent_decisions (
  id uuid default gen_random_uuid() not null,
  org_id uuid,
  agent_id text,
  decision_type text,
  entity_type text,
  entity_id uuid,
  reasoning text,
  confidence_score integer,
  action_taken text,
  required_human_review boolean default false,
  human_reviewed_at timestamptz,
  human_verdict text,
  created_at timestamptz default now(),
  agent_run_id uuid,
  action_payload jsonb default '{}',
  human_reviewer_id uuid
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'agent_decisions_pkey'
  ) then
    alter table agent_decisions add constraint agent_decisions_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- agent_queue (14 columns, from production live-schema.json)
create table if not exists agent_queue (
  id uuid default gen_random_uuid() not null,
  org_id uuid,
  agent_id text,
  priority integer default 5,
  status text default 'queued',
  trigger_source text,
  input_payload jsonb,
  output_payload jsonb,
  error_message text,
  queued_at timestamptz default now(),
  started_at timestamptz,
  completed_at timestamptz,
  retry_count integer default 0,
  max_retries integer default 3
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'agent_queue_pkey'
  ) then
    alter table agent_queue add constraint agent_queue_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- agent_runs (20 columns, from production live-schema.json)
create table if not exists agent_runs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  agent_type text,
  status text default 'pending',
  input_params jsonb,
  output_summary text,
  items_found integer default 0,
  items_processed integer default 0,
  error_message text,
  tokens_used integer,
  duration_ms integer,
  triggered_by uuid,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz default now(),
  trigger_source text default 'manual',
  next_action text,
  confidence_score integer,
  items_queued integer default 0,
  output_payload jsonb default '{}'
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'agent_runs_pkey'
  ) then
    alter table agent_runs add constraint agent_runs_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- agent_registry (11 columns, from production live-schema.json)
create table if not exists agent_registry (
  agent_id text,
  name text,
  description text,
  version text default '1.0',
  plan_requirement text default 'starter',
  trigger_type text default 'manual',
  schedule_cron text,
  avg_runtime_seconds integer,
  active boolean default true,
  created_at timestamptz default now(),
  avg_tokens_per_run integer
);

-- agent_configurations (10 columns, from production live-schema.json)
create table if not exists agent_configurations (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  agent_id text,
  enabled boolean default false,
  config jsonb default '{}',
  last_run_at timestamptz,
  run_count integer default 0,
  total_tokens_consumed integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'agent_configurations_pkey'
  ) then
    alter table agent_configurations add constraint agent_configurations_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- alerts (18 columns, from production live-schema.json)
create table if not exists alerts (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  type text,
  severity text default 'info',
  message text,
  link text,
  is_read boolean default false,
  read_at timestamptz,
  is_dismissed boolean default false,
  dismissed_at timestamptz,
  snoozed_until timestamptz,
  opportunity_id uuid,
  application_id uuid,
  deadline_id uuid,
  dedup_key text,
  created_by uuid,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'alerts_pkey'
  ) then
    alter table alerts add constraint alerts_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- application_documents (4 columns, from production live-schema.json)
create table if not exists application_documents (
  id uuid default gen_random_uuid() not null,
  application_id uuid,
  document_id uuid,
  created_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'application_documents_pkey'
  ) then
    alter table application_documents add constraint application_documents_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- autoapply_submissions (26 columns, from production live-schema.json)
create table if not exists autoapply_submissions (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  funder_id uuid,
  form_template_id uuid,
  status text default 'queued',
  request_description text,
  request_type text,
  request_amount numeric,
  pre_submit_screenshot_url text,
  confirmation_screenshot_url text,
  confirmation_number text,
  error_message text,
  error_screenshot_url text,
  retry_count integer default 0,
  next_retry_at timestamptz,
  submitted_at timestamptz,
  created_at timestamptz default now(),
  request_profile_id uuid,
  submission_channel text default 'web_form',
  personalized_pitch text,
  optimized_amount numeric,
  timing_score numeric,
  confirmation_data jsonb,
  documents_attached text[],
  confirmation_email_received boolean default false,
  confirmation_received_at timestamptz
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'autoapply_submissions_pkey'
  ) then
    alter table autoapply_submissions add constraint autoapply_submissions_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- automation_sessions (22 columns, from production live-schema.json)
create table if not exists automation_sessions (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  application_id uuid,
  opportunity_id uuid,
  funder_id uuid,
  status text default 'pending',
  target_url text,
  mapped_fields jsonb default '[]',
  unmapped_fields jsonb default '[]',
  confirmation_number text,
  error_message text,
  notes text,
  started_by uuid,
  approved_by uuid,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  session_type text,
  steps jsonb default '[]',
  screenshots text[] default '{}'::text[],
  approval_required_at timestamptz
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'automation_sessions_pkey'
  ) then
    alter table automation_sessions add constraint automation_sessions_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- board_members (11 columns, from production live-schema.json)
create table if not exists board_members (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  name text,
  title text,
  bio text,
  email text,
  phone text,
  start_date date,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'board_members_pkey'
  ) then
    alter table board_members add constraint board_members_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- community_need_signals (12 columns, from production live-schema.json)
create table if not exists community_need_signals (
  id uuid default gen_random_uuid() not null,
  org_id uuid,
  signal_source text,
  signal_category text,
  signal_description text,
  geographic_area text,
  trend_direction text,
  severity text,
  predicted_demand_increase integer,
  recommended_program_expansion text,
  data_date date,
  created_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'community_need_signals_pkey'
  ) then
    alter table community_need_signals add constraint community_need_signals_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- corporate_intent_signals (13 columns, from production live-schema.json)
create table if not exists corporate_intent_signals (
  id uuid default gen_random_uuid() not null,
  org_id uuid,
  company_name text,
  signal_type text,
  signal_summary text,
  signal_url text,
  signal_date date,
  intent_score integer,
  geographic_relevance integer,
  mission_alignment integer,
  recommended_action text,
  recommended_deadline date,
  created_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'corporate_intent_signals_pkey'
  ) then
    alter table corporate_intent_signals add constraint corporate_intent_signals_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- corporate_prospects (40 columns, from production live-schema.json)
create table if not exists corporate_prospects (
  id uuid default gen_random_uuid() not null,
  legal_name text,
  dba_name text,
  ein text,
  duns_number text,
  website text,
  phone text,
  email text,
  address_street text,
  address_city text,
  address_state text,
  address_zip text,
  address_lat numeric,
  address_lng numeric,
  naics_code text,
  naics_description text,
  sic_code text,
  industry_category text,
  employee_count_estimate text,
  revenue_estimate text,
  location_count integer,
  geographic_footprint text[],
  ownership_type text,
  is_family_owned boolean,
  is_veteran_owned boolean,
  is_minority_owned boolean,
  is_woman_owned boolean,
  parent_company_id uuid,
  source_adapters text[],
  first_seen_at timestamptz default now(),
  last_verified_at timestamptz,
  enrichment jsonb default '{}',
  enrichment_version integer default 0,
  enrichment_started_at timestamptz,
  enrichment_completed_at timestamptz,
  scores jsonb default '{}',
  scores_computed_at timestamptz,
  giving_dna jsonb default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'corporate_prospects_pkey'
  ) then
    alter table corporate_prospects add constraint corporate_prospects_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- documents (12 columns, from production live-schema.json)
create table if not exists documents (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  file_name text,
  storage_path text,
  file_size bigint,
  mime_type text,
  category text,
  description text,
  expiration_date date,
  uploaded_by uuid,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'documents_pkey'
  ) then
    alter table documents add constraint documents_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- donor_discovery_directory (15 columns, from production live-schema.json)
create table if not exists donor_discovery_directory (
  id uuid default gen_random_uuid() not null,
  legal_name text,
  dba_name text,
  naics_codes text[] default '{}'::text[],
  civic_kind text,
  website text,
  hq_address text,
  geo point,
  phone text,
  enrichment jsonb default '{}',
  enriched_at timestamptz,
  source_adapters text[] default '{}'::text[],
  created_at timestamptz default now(),
  linked_foundation_id uuid,
  linkage_confidence numeric
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'donor_discovery_directory_pkey'
  ) then
    alter table donor_discovery_directory add constraint donor_discovery_directory_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- donor_discovery_requests (10 columns, from production live-schema.json)
create table if not exists donor_discovery_requests (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  name text,
  taxonomy_ids text[] default '{}'::text[],
  geography jsonb default '{}',
  status text default 'queued',
  counts jsonb default '{}',
  created_by uuid,
  created_at timestamptz default now(),
  completed_at timestamptz
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'donor_discovery_requests_pkey'
  ) then
    alter table donor_discovery_requests add constraint donor_discovery_requests_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- email_activity (16 columns, from production live-schema.json)
create table if not exists email_activity (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  funder_id uuid,
  opportunity_id uuid,
  application_id uuid,
  email_type text,
  subject text,
  sender text,
  received_at timestamptz,
  summary text,
  action_required boolean default false,
  action_description text,
  urgency text default 'low',
  thread_id text,
  processed_at timestamptz default now(),
  created_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'email_activity_pkey'
  ) then
    alter table email_activity add constraint email_activity_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- form_templates (18 columns, from production live-schema.json)
create table if not exists form_templates (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  funder_id uuid,
  portal_url text,
  form_structure jsonb,
  field_mapping jsonb,
  is_multi_step boolean default false,
  step_navigation jsonb,
  requires_login boolean default false,
  requires_file_upload boolean default false,
  file_upload_fields jsonb,
  last_verified_at timestamptz,
  last_used_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  auto_generated boolean default false,
  field_count integer,
  automation_assessment jsonb
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'form_templates_pkey'
  ) then
    alter table form_templates add constraint form_templates_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- foundation_directory (35 columns, from production live-schema.json)
create table if not exists foundation_directory (
  id uuid default gen_random_uuid() not null,
  ein text,
  name text,
  dba text,
  city text,
  state text,
  zip text,
  ntee_code text,
  subsection_code text,
  foundation_type text,
  revenue_amount numeric,
  asset_amount numeric,
  ruling_date text,
  tax_period text,
  activity_codes text,
  organization_type text,
  status text,
  website text,
  email text,
  phone text,
  giving_total numeric,
  geographic_focus text,
  imported_at timestamptz default now(),
  created_at timestamptz default now(),
  enriched_at timestamptz,
  enrichment_source text,
  officers jsonb default '[]',
  programs text[],
  contact_emails text[] default '{}'::text[],
  contact_phones text[] default '{}'::text[],
  enrichment jsonb default '{}',
  enriched_990_at timestamptz,
  enriched_web_at timestamptz,
  website_discovered_via text,
  embedding text
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'foundation_directory_pkey'
  ) then
    alter table foundation_directory add constraint foundation_directory_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- fundability_scores (10 columns, from production live-schema.json)
create table if not exists fundability_scores (
  id uuid default gen_random_uuid() not null,
  org_id uuid,
  opportunity_id uuid,
  overall_score integer,
  probability_without_fixes integer,
  probability_with_fixes integer,
  confidence text,
  deficiencies jsonb default '[]',
  recommendation text,
  generated_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fundability_scores_pkey'
  ) then
    alter table fundability_scores add constraint fundability_scores_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- funder_dna_profiles (14 columns, from production live-schema.json)
create table if not exists funder_dna_profiles (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  funder_id uuid,
  requirement_patterns jsonb default '{}',
  reward_patterns jsonb default '{}',
  typical_award_range_min numeric,
  typical_award_range_max numeric,
  common_eligibility_themes text[],
  common_required_documents text[],
  sample_size integer default 0,
  confidence numeric,
  last_analyzed_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'funder_dna_profiles_pkey'
  ) then
    alter table funder_dna_profiles add constraint funder_dna_profiles_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- funder_relationship_scores (16 columns, from production live-schema.json)
create table if not exists funder_relationship_scores (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  funder_id uuid,
  score integer default 0,
  events jsonb default '[]',
  last_updated_at timestamptz default now(),
  created_at timestamptz default now(),
  relationship_score integer default 0,
  total_interactions integer default 0,
  successful_applications integer default 0,
  last_interaction_at timestamptz,
  notes text,
  updated_at timestamptz default now(),
  trend text default 'neutral',
  recent_events jsonb default '[]',
  is_stale boolean default false
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'funder_relationship_scores_pkey'
  ) then
    alter table funder_relationship_scores add constraint funder_relationship_scores_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- opportunity_probability_scores (12 columns, from production live-schema.json)
create table if not exists opportunity_probability_scores (
  id uuid default gen_random_uuid() not null,
  opportunity_id uuid,
  organization_id uuid,
  overall_score integer default 0,
  confidence text default 'low',
  factors jsonb default '[]',
  recommendation text default 'consider',
  key_risks text[],
  key_strengths text[],
  estimated_roi text,
  time_to_complete text,
  computed_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'opportunity_probability_scores_pkey'
  ) then
    alter table opportunity_probability_scores add constraint opportunity_probability_scores_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- outcomes (16 columns, from production live-schema.json)
create table if not exists outcomes (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  application_id uuid,
  result text,
  awarded_amount numeric,
  requested_amount numeric,
  funder_feedback text,
  denial_reason text,
  narrative_snapshot text,
  funder_category text,
  opportunity_category text,
  keywords_used text[],
  recorded_by uuid,
  recorded_at timestamptz default now(),
  created_at timestamptz default now(),
  embedding text
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'outcomes_pkey'
  ) then
    alter table outcomes add constraint outcomes_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- outreach_contacts (15 columns, from production live-schema.json)
create table if not exists outreach_contacts (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  company_name text,
  contact_name text,
  email text,
  phone text,
  contact_form_url text,
  source_url text,
  company_type text,
  giving_likelihood text,
  campaign_id uuid,
  status text default 'new',
  converted_to_funder_id uuid,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'outreach_contacts_pkey'
  ) then
    alter table outreach_contacts add constraint outreach_contacts_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- pig_edges (9 columns, from production live-schema.json)
create table if not exists pig_edges (
  id uuid default gen_random_uuid() not null,
  source_node_id uuid,
  target_node_id uuid,
  relationship_type text,
  weight numeric default 1.0,
  evidence text,
  verified boolean default false,
  metadata jsonb default '{}',
  discovered_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'pig_edges_pkey'
  ) then
    alter table pig_edges add constraint pig_edges_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- pig_nodes (8 columns, from production live-schema.json)
create table if not exists pig_nodes (
  id uuid default gen_random_uuid() not null,
  node_type text,
  entity_id uuid,
  entity_table text,
  label text,
  metadata jsonb default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'pig_nodes_pkey'
  ) then
    alter table pig_nodes add constraint pig_nodes_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- platform_learning_patterns (11 columns, from production live-schema.json)
create table if not exists platform_learning_patterns (
  id uuid default gen_random_uuid() not null,
  pattern_type text,
  funder_category text,
  ntee_code text,
  pattern_content text,
  success_rate numeric,
  sample_count integer default 1,
  avg_award_amount numeric,
  winning_examples jsonb default '[]',
  last_updated timestamptz default now(),
  created_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'platform_learning_patterns_pkey'
  ) then
    alter table platform_learning_patterns add constraint platform_learning_patterns_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- proven_narratives (12 columns, from production live-schema.json)
create table if not exists proven_narratives (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  outcome_id uuid,
  knowledge_base_id uuid,
  narrative_text text,
  section_type text,
  funder_category text,
  success_count integer default 1,
  effectiveness_score numeric,
  last_used_at timestamptz,
  created_at timestamptz default now(),
  success_patterns jsonb
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'proven_narratives_pkey'
  ) then
    alter table proven_narratives add constraint proven_narratives_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- relationship_memory (9 columns, from production live-schema.json)
create table if not exists relationship_memory (
  id uuid default gen_random_uuid() not null,
  org_id uuid,
  entity_id uuid,
  entity_type text default 'funder',
  memory_type text,
  content text,
  signal_date date,
  actioned boolean default false,
  created_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'relationship_memory_pkey'
  ) then
    alter table relationship_memory add constraint relationship_memory_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- relationship_recommendations (8 columns, from production live-schema.json)
create table if not exists relationship_recommendations (
  id uuid default gen_random_uuid() not null,
  org_id uuid,
  entity_id uuid,
  entity_type text default 'funder',
  recommendation_text text,
  urgency text default 'normal',
  status text default 'pending',
  created_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'relationship_recommendations_pkey'
  ) then
    alter table relationship_recommendations add constraint relationship_recommendations_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- reputation_signals (11 columns, from production live-schema.json)
create table if not exists reputation_signals (
  id uuid default gen_random_uuid() not null,
  entity_id uuid,
  entity_type text,
  signal_type text,
  severity text default 'yellow',
  headline text,
  summary text,
  source_url text,
  signal_date date,
  verified boolean default false,
  created_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'reputation_signals_pkey'
  ) then
    alter table reputation_signals add constraint reputation_signals_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- reputation_alerts (5 columns, from production live-schema.json)
create table if not exists reputation_alerts (
  id uuid default gen_random_uuid() not null,
  org_id uuid,
  signal_id uuid,
  status text default 'unread',
  created_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'reputation_alerts_pkey'
  ) then
    alter table reputation_alerts add constraint reputation_alerts_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- roi_insights (10 columns, from production live-schema.json)
create table if not exists roi_insights (
  id uuid default gen_random_uuid() not null,
  org_id uuid,
  insight_type text,
  insight_description text,
  winning_pattern text,
  losing_pattern text,
  sample_size integer,
  confidence numeric,
  recommended_action text,
  generated_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'roi_insights_pkey'
  ) then
    alter table roi_insights add constraint roi_insights_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- search_profiles (22 columns, from production live-schema.json)
create table if not exists search_profiles (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  name text,
  keywords text[],
  categories text[],
  geographic_scope text,
  min_amount numeric,
  max_amount numeric,
  recurrence_preference text,
  is_active boolean default true,
  last_run_at timestamptz,
  results_count integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  agent_settings jsonb default '{}',
  source_type_filters jsonb default '[]',
  focus_areas jsonb default '[]',
  geographic_scopes text[] default '{}'::text[],
  eligibility_filters jsonb default '{}',
  populations_served text[] default '{}'::text[],
  excluded_categories text[] default '{}'::text[],
  excluded_funders text[] default '{}'::text[]
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'search_profiles_pkey'
  ) then
    alter table search_profiles add constraint search_profiles_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- submission_queue (20 columns, from production live-schema.json)
create table if not exists submission_queue (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  funder_id uuid,
  priority integer default 100,
  status text default 'pending',
  automation_mode text default 'manual',
  scheduled_for timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  submission_id uuid,
  created_at timestamptz default now(),
  request_profile_id uuid,
  pause_reason text,
  paused_at timestamptz,
  paused_screenshot_path text,
  paused_history jsonb default '[]',
  resume_count integer default 0,
  error_message text,
  risk_score integer,
  risk_factors jsonb
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'submission_queue_pkey'
  ) then
    alter table submission_queue add constraint submission_queue_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- usage_metrics (7 columns, from production live-schema.json)
create table if not exists usage_metrics (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  metric_date date,
  metric_name text,
  metric_value bigint default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'usage_metrics_pkey'
  ) then
    alter table usage_metrics add constraint usage_metrics_pkey primary key (id);
  end if;
exception when others then null;
end $$;

-- org_autonomous_config (23 columns, from production live-schema.json)
create table if not exists org_autonomous_config (
  id uuid default gen_random_uuid() not null,
  org_id uuid,
  auto_research_enabled boolean default false,
  auto_score_enabled boolean default false,
  auto_draft_enabled boolean default false,
  auto_draft_threshold integer default 70,
  auto_reputation_enabled boolean default false,
  auto_relationship_enabled boolean default false,
  auto_deadline_prediction_enabled boolean default false,
  auto_followup_enabled boolean default false,
  max_auto_drafts_per_night integer default 10,
  created_at timestamptz default now(),
  auto_fundability_enabled boolean default false,
  auto_donor_intent_enabled boolean default false,
  auto_community_need_enabled boolean default false,
  auto_strategic_advisor_enabled boolean default false,
  notify_on_auto_draft boolean default true,
  notify_on_high_score boolean default true,
  notify_digest_time text default '07:00',
  updated_at timestamptz default now(),
  auto_autoapply_enabled boolean default false,
  max_nightly_autoapply_submissions integer default 50,
  auto_deploy_disaster_response boolean default false
);
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'org_autonomous_config_pkey'
  ) then
    alter table org_autonomous_config add constraint org_autonomous_config_pkey primary key (id);
  end if;
exception when others then null;
end $$;
