import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - Benavora",
  description:
    "The terms governing your use of Benavora's grant automation platform.",
};

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-10">
      <h2 className="text-xl font-semibold text-white">{title}</h2>
      <div className="mt-3 space-y-3 text-[15px] leading-relaxed text-gray-300">
        {children}
      </div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
        Terms of Service
      </h1>
      <p className="mt-3 text-sm text-gray-500">Last updated: June 2026</p>

      <Section title="1. Acceptance of Terms">
        <p>
          These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and
          use of Benavora (&ldquo;Benavora,&rdquo; &ldquo;we,&rdquo; or
          &ldquo;us&rdquo;). By creating an account or using the service, you
          agree to these Terms on behalf of yourself and the organization you
          represent. If you do not agree, do not use the service.
        </p>
      </Section>

      <Section title="2. Description of Service">
        <p>
          Benavora is a nonprofit funding-automation platform. Its features
          include:
        </p>
        <ul className="list-disc space-y-1 pl-5">
          <li>
            <span className="text-gray-200">Grant discovery</span> &mdash;
            research agents that surface federal, state, and foundation funding
            opportunities matched to your organization.
          </li>
          <li>
            <span className="text-gray-200">AI drafts</span> &mdash;
            AI-generated grant narratives, letters, budgets, and impact
            statements grounded in your Knowledge Base.
          </li>
          <li>
            <span className="text-gray-200">AutoApply</span> &mdash; optional
            automated completion and submission of funder application forms on
            your behalf.
          </li>
        </ul>
      </Section>

      <Section title="3. Subscriptions &amp; Fees">
        <p>Benavora is offered on the following monthly subscription tiers:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>
            <span className="text-gray-200">Starter</span> &mdash; $249/month.
          </li>
          <li>
            <span className="text-gray-200">Professional</span> &mdash;
            $599/month.
          </li>
          <li>
            <span className="text-gray-200">Enterprise</span> &mdash;
            $1,999/month.
          </li>
        </ul>
        <p>
          Fees are billed in advance and are non-refundable except where
          required by law. Plans renew automatically until cancelled. We may
          change pricing with at least 30 days&rsquo; notice; changes apply to
          your next billing cycle. Taxes are your responsibility where
          applicable.
        </p>
      </Section>

      <Section title="4. Acceptable Use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>use the service for any unlawful or fraudulent purpose;</li>
          <li>
            submit false information to funders or misrepresent your
            organization;
          </li>
          <li>
            attempt to access another organization&rsquo;s data, reverse
            engineer, or disrupt the service;
          </li>
          <li>
            use AutoApply against portals where automated submission is
            prohibited by the funder&rsquo;s terms; or
          </li>
          <li>resell or sublicense the service without our written consent.</li>
        </ul>
      </Section>

      <Section title="5. AI-Generated Content Disclaimer">
        <p>
          AI-generated drafts are provided as a starting point and may contain
          inaccuracies, omissions, or content requiring verification. You are
          solely responsible for reviewing, editing, and approving all content
          before submission. Benavora does not guarantee funding outcomes,
          accuracy, or eligibility. Nothing generated by the service is legal,
          financial, or professional advice.
        </p>
      </Section>

      <Section title="6. AutoApply Disclaimer">
        <p>
          AutoApply submits applications using the information you provide and
          the authorization you grant. You are responsible for the accuracy and
          completeness of every submission and for ensuring that automated
          submission complies with each funder&rsquo;s rules. Benavora is not
          liable for rejected, incomplete, late, or duplicate submissions, or
          for actions taken by funder portals. Review submissions before and
          after they are sent.
        </p>
      </Section>

      <Section title="7. Intellectual Property">
        <p>
          Benavora and its software, design, and trademarks are owned by us and
          protected by law. We grant you a limited, non-exclusive,
          non-transferable license to use the service during your subscription.
          You retain ownership of the organizational content you provide and the
          final applications you produce; you grant us a license to process that
          content solely to operate and improve the service.
        </p>
      </Section>

      <Section title="8. Limitation of Liability">
        <p>
          To the maximum extent permitted by law, the service is provided
          &ldquo;as is&rdquo; without warranties of any kind. Benavora will not
          be liable for any indirect, incidental, special, consequential, or
          punitive damages, or for lost funding, profits, data, or goodwill. Our
          total liability for any claim arising out of or relating to the
          service is limited to the amount you paid us in the twelve months
          before the claim.
        </p>
      </Section>

      <Section title="9. Termination">
        <p>
          You may cancel your subscription at any time; access continues through
          the end of the paid period. We may suspend or terminate your account
          for violation of these Terms, non-payment, or as required by law. On
          termination, your license to use the service ends and we will handle
          your data as described in our Privacy Policy.
        </p>
      </Section>

      <Section title="10. Governing Law">
        <p>
          These Terms are governed by the laws of the State of Delaware, without
          regard to its conflict-of-laws principles. Any dispute will be brought
          exclusively in the state or federal courts located in Delaware, and
          you consent to their jurisdiction.
        </p>
      </Section>

      <Section title="11. Contact Us">
        <p>
          Questions about these Terms? Email{" "}
          <a
            href="mailto:support@benavora.com"
            className="text-orange-400 hover:text-orange-300"
          >
            support@benavora.com
          </a>
          .
        </p>
      </Section>
    </div>
  );
}
