-- 075_donor_discovery_taxonomy_aliases.sql — plain-language aliases for
-- donor_discovery_taxonomy (DONOR_DISCOVERY_ARCHITECTURE.md §1A-1C).
--
-- A nonprofit staffer searching "septic installer" won't find NAICS 562991
-- ("Septic Tank and Related Services") by label text alone. This table maps
-- each taxonomy node to the trade names/keywords a human would actually type,
-- generated by scripts/seed-dd-aliases.ts and consumed by
-- /api/donor-discovery/taxonomy/search.
--
-- Same posture as donor_discovery_taxonomy itself: no organization_id, no
-- RLS — shared reference data seeded once, subscribers only read it.

CREATE TABLE IF NOT EXISTS donor_discovery_taxonomy_aliases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), taxonomy_id uuid NOT NULL REFERENCES donor_discovery_taxonomy(id) ON DELETE CASCADE, alias text NOT NULL, alias_type text NOT NULL DEFAULT 'trade_name' CHECK (alias_type IN ('trade_name','keyword','common_name','material')), created_at timestamptz DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_dd_taxonomy_aliases_taxonomy_id ON donor_discovery_taxonomy_aliases(taxonomy_id);
CREATE INDEX IF NOT EXISTS idx_dd_taxonomy_aliases_alias_trgm ON donor_discovery_taxonomy_aliases USING gin(alias gin_trgm_ops);
